# Pandas for data analysis
         - Series
         - Data Frame

# Series:
    Data with single column/feature

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series(['Chairs','Tables','Keybords', 'Mouse','Monitor'],name='Furniture')
s1

0      Chairs
1      Tables
2    Keybords
3       Mouse
4     Monitor
Name: Furniture, dtype: object

In [3]:
s1.values

array(['Chairs', 'Tables', 'Keybords', 'Mouse', 'Monitor'], dtype=object)

In [4]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s1.name

'Furniture'

In [6]:
s1.dtype

dtype('O')

In [7]:
# index with srtring values are called labels
s1 = pd.Series(data=[10,36,12,50,100],index=['Chairs','Tables','Keybords', 'Mouse','Monitor'],name='Furniture')
s1

Chairs       10
Tables       36
Keybords     12
Mouse        50
Monitor     100
Name: Furniture, dtype: int64

In [8]:
df = pd.DataFrame({'Furniture' :['Chairs','Tables','Keybords', 'Mouse','Monitor'],
                   'Quantity'  :[10,36,12,50,100],
                   'City'      :['Khi','Hyd','Lhr','Khi','Hyd']
                  })

In [9]:
df

  Furniture  Quantity City
0    Chairs        10  Khi
1    Tables        36  Hyd
2  Keybords        12  Lhr
3     Mouse        50  Khi
4   Monitor       100  Hyd

In [12]:
df = pd.read_excel('employee.xlsx')

In [13]:
df

    Serial  Emp_ID Designation  Department   Age    Salary
0        0    1101     Manager    Accounts  50.0  200000.0
1        1    1107     Officer          IT  30.0   80000.0
2        2    1203     Officer          HR  28.0       NaN
3        3    1005     Manager          HR  45.0  120000.0
4        4    2123  Office Boy    Accounts  27.0   45000.0
5        5    2451  Accountant         NaN  34.0  100000.0
6        6    1111  Accountant    Accounts   NaN  110000.0
7        7    1001     Officer          IT  25.0   75000.0
8        8    1234     Manager          IT  23.0       NaN
9        9    2156    Engineer  Production  45.0   89000.0
10      10    6543     Officer  Production  29.0  100000.0
11      11    3214  Accountant     Account  49.0  123000.0
12      12    2156    Engineer  Production  45.0   89000.0
13      13    1098     Officer          IT  25.0  100000.0
14      14    2912     Officer          IT  31.0   90000.0
15      15    1222     Officer         NaN  25.0       NaN
16      16    2156    Engineer  Production  45.0   89000.0
17      17    2123  Office Boy    Accounts  27.0   45000.0
18      18    1005     Manager          HR  45.0  120000.0
19      19    2123  Office Boy    Accounts  27.0   45000.0
20      20    6543     Officer  Production  29.0  100000.0
21      21    3214  Accountant     Account  49.0  123000.0
22      22    2156    Engineer  Production  45.0   89000.0
23      23    1098     Officer          IT  25.0  100000.0
24      24    2156    Engineer  Production  45.0   89000.0
25      25    2123  Office Boy    Accounts  27.0   45000.0

In [14]:
df['Department']

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5            NaN
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15           NaN
16    Production
17      Accounts
18            HR
19      Accounts
20    Production
21       Account
22    Production
23            IT
24    Production
25      Accounts
Name: Department, dtype: object

In [15]:
df.Department

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5            NaN
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15           NaN
16    Production
17      Accounts
18            HR
19      Accounts
20    Production
21       Account
22    Production
23            IT
24    Production
25      Accounts
Name: Department, dtype: object

In [18]:
df[['Emp_ID','Department','Age']]

    Emp_ID  Department   Age
0     1101    Accounts  50.0
1     1107          IT  30.0
2     1203          HR  28.0
3     1005          HR  45.0
4     2123    Accounts  27.0
5     2451         NaN  34.0
6     1111    Accounts   NaN
7     1001          IT  25.0
8     1234          IT  23.0
9     2156  Production  45.0
10    6543  Production  29.0
11    3214     Account  49.0
12    2156  Production  45.0
13    1098          IT  25.0
14    2912          IT  31.0
15    1222         NaN  25.0
16    2156  Production  45.0
17    2123    Accounts  27.0
18    1005          HR  45.0
19    2123    Accounts  27.0
20    6543  Production  29.0
21    3214     Account  49.0
22    2156  Production  45.0
23    1098          IT  25.0
24    2156  Production  45.0
25    2123    Accounts  27.0

In [20]:
df.Age.min()

23.0

In [21]:
df.Age.max()

50.0

In [22]:
df.Age.mean()

35.0

In [23]:
df.Age.std()

9.746794344808963

In [24]:
df.Age.var()

95.0